version: '2.4'

#networks:
#  sandbox:

services:

  sql:
    image: ${REGISTRY}sitecore-xp-sxa-sqldev:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
 #   networks:
 #     sandbox:
    volumes:
      - .\data\sql:C:\Data
    mem_limit: 2GB
    ports:
      - "44010:1433"

  solr:
    image: ${REGISTRY}sitecore-xp-sxa-solr:${SITECORE_VERSION}-nanoserver-${NANOSERVER_VERSION}
#    networks:
#      sandbox:
    volumes:
      - .\data\solr:C:\Data
    mem_limit: 1GB
    ports:
      - "44011:8983"

  xconnect:
    image: ${REGISTRY}sitecore-xp-xconnect:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect:C:\inetpub\wwwroot\App_Data\logs
    mem_limit: 1GB
    links:
      - sql
      - solr

  xconnect-automationengine:
    image: ${REGISTRY}sitecore-xp-xconnect-automationengine:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
#    networks:
#      sandbox:
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect-automationengine:C:\AutomationEngine\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - xconnect

  xconnect-indexworker:
    image: ${REGISTRY}sitecore-xp-xconnect-indexworker:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
#    networks:
#      sandbox:
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect-indexworker:C:\IndexWorker\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - solr

  xconnect-processingengine:
    image: ${REGISTRY}sitecore-xp-xconnect-processingengine:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
#    networks:
#      sandbox:
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\xconnect-processingengine:C:\ProcessingEngine\App_Data\logs
    mem_limit: 500MB
    restart: unless-stopped
    links:
      - sql
      - xconnect

  cd:
    image: ${REGISTRY}sitecore-xp-sxa-cd:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
#    networks:
#      sandbox:
#        aliases:
#          - sandbox-cd.local
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\cd\wwwroot:C:\inetpub\wwwroot
    ports:
      - "44002:80"
    links:
      - sql
      - solr
      - xconnect

  cm:
    image: ${REGISTRY}sitecore-xp-sxa-standalone:${SITECORE_VERSION}-windowsservercore-${WINDOWSSERVERCORE_VERSION}
#    networks:
#      sandbox:
#        aliases:
#          - sandbox-cms.local
    volumes:
      - ${LICENSE_PATH}:C:\license
      - .\data\cm\wwwroot:C:\inetpub\wwwroot
    ports:
      - "44001:80"
    links:
      - sql
      - solr
      - xconnect
