---
ID: "ba853104-7942-42b6-b1b4-e81e62fffe79"
Parent: "b741b17b-67b2-4dd8-a216-d092813871f0"
Template: "6d1cd897-1936-4a3a-a511-289a94c2a7b1"
Path: "/sitecore/content/Basic Company/Dictionary/Products-RelatedProducts-Title"
DB: master
SharedFields:
- ID: "580c75a8-c01a-4580-83cb-987776ceb3af"
  Hint: Key
  Value: "Products-RelatedProducts-Title"
Languages:
- Language: en
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: Related Products
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190503T192107Z
