---
ID: "4f6e9ea5-92f0-4c16-bc78-a318bace2838"
Parent: "abcecb30-2777-48c7-8860-813e5268816c"
Template: "abcecb30-2777-48c7-8860-813e5268816c"
Path: /sitecore/templates/Feature/Products/_Product/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190312T195116Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "be500a38-36a0-417b-86c5-e63ba71d0939"
      Hint: Title
      Value: $name
