---
ID: "d91b7c6d-a10e-4b72-8327-5df0a8d79093"
Parent: "d14d4ff5-9eb0-409f-8503-4b5e7fb1ad1b"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Products/Product List
DB: master
SharedFields:
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: BasicCompany.Feature.Products.Controllers.ProductsController, BasicCompany.Feature.Products
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: List
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/16x16/book.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190312T191922Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "77dec615-563f-41fc-9162-f20bec936d3f"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190930T183109Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
