---
ID: "eeafadce-cfcf-4734-90c1-4361482b1674"
Parent: "4a421518-7b4a-4d43-af9b-94e17e00ec9f"
Template: "4a421518-7b4a-4d43-af9b-94e17e00ec9f"
Path: /sitecore/templates/Feature/BasicContent/Hero Banner/__Standard Values
DB: master
Created: 20190930T183114Z
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190311T190830Z
    - ID: "5179186c-b95e-4e97-95ab-7958721a9aeb"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f81d7a27-ad5d-4b1d-b3d2-1a1d55cd5e84"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190930T183114Z
