---
ID: "6e7d9a62-b995-4109-ab0d-0dc153764df5"
Parent: "7972f31a-628d-40dd-bc51-1f1fbc93adfb"
Template: "fcb0ba21-9aaa-45f8-b86c-738fb269e06f"
Path: /sitecore/content/Basic Company/Home/Services/Page Components/Services
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190507T145919Z
    - ID: "59d24d0a-f955-4988-b26f-92039b4df8bd"
      Hint: Text
      Value: Services
